### ISSUE TITLE
Setup.py missing requirement Matplotlib

### ISSUE THREAD

**Issue by alxschwrz** [maxspahn/gym_envs_urdf#1]
When installing the `gym_envs_urdf` dependencies through the `setup.py` file using

`pip3 install -e .`

the setup is missing matplotlib when running the examples. Adding matplotlib to `setup.py` should resolve this.

**Comment by maxspahn** [comment]
Urdf2casadi and rbdl are only required for inverse dynamics. When using the pybullet dynamics solver, the dependencies could be removed.

**Comment by alxschwrz** [comment]
how would I run the pandaReacher without urdf2casadi and rbdl?
