### ISSUE TITLE
Add Isaac Gym Environment

### ISSUE THREAD

**Issue by SkyloveQiu** [maxspahn/gym_envs_urdf#134]

**Comment by c-salmi** [comment]
Hi Qiu,

Heard you were working on this but was not able to test it due to your laptop specs not having enough gpu vram. I'm actually also interested in adding this option. Could you push your work to a dedicated branch for this new feature?

**Comment by SkyloveQiu** [comment]
Hi chadi:
The gym.make function is not working, I did not find a replacement function from the documentation, do you know which function replaces the original gym.make?

**Comment by SkyloveQiu** [comment]
`robots = [
        AlbertRobot(mode="vel"),
    ]
    env = gym.make(
        "urdf-env-v0",
        dt=0.01, robots=robots, render=render
    )`

The code I am referring to.

**Comment by SkyloveQiu** [comment]
@c-salmi [Link](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs) this could help I believe

**Comment by SkyloveQiu** [comment]
@c-salmi [start point](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/isaacgymenvs/tasks/base/vec_task.py) I have found this `VecTask` class which could be our start point.

**Comment by c-salmi** [comment]
@SkyloveQiu Yes exactly their `step` method implementation would be a good reference to see how we can convert our [step](https://github.com/maxspahn/gym_envs_urdf/blob/2bb2159f9f44cb3171d8b638129cf2e149f90106/urdfenvs/urdf_common/urdf_env.py#L227) from pybullet to isaacgym.

**Comment by SkyloveQiu** [comment]
Probably we are not going to make our step into issacgymenv, let's implement everything from scratch and build it with openai gym, more people can use our project to replace their pybullet.

**Comment by maxspahn** [comment]
In a first step, let's separate the physics engine from the rest. I started doing this in https://github.com/maxspahn/gym_envs_urdf/tree/ft-separate-physics-engine

**Comment by maxspahn** [comment]
Closing as this integration is put on hold in favor of integrating MuJoCo instead.
