### ISSUE TITLE
Installing pybullet on windows

### ISSUE THREAD

**Issue by maxspahn** [maxspahn/gym_envs_urdf#137]
Many people try to use the simulation environment on Windows. 
For most people this results in errors for the package ```pybullet``` as it requires a specific c++ compiler.
Let us gather information and problems related to this in this issue.

**Comment by DasWilheim** [comment]
Following this instruction on stackflow worked for me.

https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

**Comment by behradkhadem** [comment]
I use WSL2 to tackle this issue. With Ubuntu subsystem you won't need a C++ compiler or else to run pybullet. You can simply just install it as a python package and use it. By using subsystems, you have flexibility of Linux with UX of windows. Also, you can run Linux GUI on Windows too, for that you will need [XLaunch](https://x.cygwin.com/docs/xlaunch/).
If you want, I can write some docs with pictures and stuff. 

![image](https://user-images.githubusercontent.com/31148015/227963709-b527d1db-2eee-4b0b-9ecd-f2d722ee2382.png)

**Comment by maxspahn** [comment]
@behradkhadem Thanks for pointing that out! If you could write some docs, and create a PR that would be very much welcome. I don't use windows personally, so it is hard for me to test it on windows.
Let me know if you need any help, also concerning the workflow.

**Comment by behradkhadem** [comment]
> @behradkhadem Thanks for pointing that out! If you could write some docs, and create a PR that would be very much welcome. I don't use windows personally, so it is hard for me to test it on windows.
> Let me know if you need any help, also concerning the workflow.

Sure, I'll look into it at the weekend!

**Comment by maxspahn** [comment]
Closed as docs were updated by @behradkhadem
