### ISSUE TITLE
path to imports if repository is used as git submodule

### ISSUE THREAD

**Issue by GijsGroote** [maxspahn/gym_envs_urdf#19]
Cloning the gym_envs_urdf repository as git submodule:

```git submodule add https://github.com/maxspahn/gym_envs_urdf```

does not edit the import paths in the module. This results in a ModuleNotFoundError.

possible temporary solution, is adding the relative path from the working directory to the gym_envs_urdf/ directory

```
import sys
sys.path.insert(0, "/home/gijs/Documents/semantic-thinking-robot/gym_envs_urdf/")
```

or editing the import paths in every file of the module, an example is editing:

```
from tiagoReacher.envs.tiagoReacherEnv import TiagoReacherEnv
```
to:
```
from gym_envs_urdf.tiagoReacher.envs.tiagoReacherEnv import TiagoReacherEnv
```

**Comment by maxspahn** [comment]
How exactly do you install the submodule?
Dose the error persist if you install the package through pip install?

Generally, I don't really think that the gym should be used as submodule, but rather installed as its own package. This is only a comment and does not solve the issue.

**Comment by GijsGroote** [comment]
Create a new github repository and clone.  Create a pycharm project in this repository.

pycharm behavior: All commands have been used inside the pycharm terminal to make sure everything is installed inside the current pycharm project called tempRepository. Create a new project and configure python

```
git clone git@github.com:maxspahn/gym_envs_urdf.git 
cd gym_envs_urdf
pip3 install -e .
git submodule add git@github.com:maxspahn/gym_envs_urdf.git gym_envs_urdf
```

Then when running any of the examples, the following error occurs:

Traceback (most recent call last):
  File "C:\Users\gijsg\Desktop\tempRepository\gym_envs_urdf\examples\albert.py", line 2, in <module>
    import albertReacher
ModuleNotFoundError: No module named 'albertReacher'

The project structure is now:

tempRepository
├───.idea
├───.git
├───.gitmodules
├───gym_envs_urdf
│   ├───albertReacher
│   ├───examples
│   ├───etc.
├───tempSrc
└───venv 

Do you mean the gym package should be used as its own module or the gym_envs_urdf should be used its own module?
In the future as we will probably use gym_envs_urdf by installing it as its own package. This will solve the issue. For now the temporarily solutions will be enough. If you agree this issue can be closed.

**Comment by maxspahn** [comment]
Thanks for all your effort!

I tried to replicate the problem by running the 4 commands you suggested in a virtual environment.
However, there is no problem despite having two clone of the same repository. 
What is the tempRepository in your example?

To clarify: Gym is already its own module. I suggested to also use gym_envs_urdf as its own module.

**Comment by GijsGroote** [comment]
Creating a project with poetry solves this problem (because poetry installs all dependencies in it's own environment unless specified otherwise) 

For completion 'tempRepository' it the name of my own project repository which uses has as one of it's dependencies gym_envs_urdf or urdf_envs.
