### ISSUE TITLE
How do I change the color of a object rendered in the environment?

### ISSUE THREAD

**Issue by bakuljangley** [maxspahn/gym_envs_urdf#246]
``` env.add_obstacle(obstacle)``` -- how do i add colors to spawned objects.

**Comment by maxspahn** [comment]
You can specify the color of an obstacle in the configuration dictionary. 

https://github.com/maxspahn/gym_envs_urdf/blob/d00397a7160e9427bee96bb762a0faaf69b9b726/urdfenvs/scene_examples/obstacles.py#L167
