### ISSUE TITLE
issue:  Problems with loading the drivers and opening swras

### ISSUE THREAD

**Issue by harmfrima** [maxspahn/gym_envs_urdf#272]
Issue: I encounter issues when running the simulation environment: gym_envs_urdf. I followed the README but get errors at the last step when I have to run the examples: python3 point_robot.py. It says I have problems with loading the drivers and opening swrast.

This is the error: 

(base) harm@harm-virtual-machine:~/Documents/help/gym_envs_urdf/examples$ python3 point_robot.py
pybullet build time: Nov 28 2023 23:45:17
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Creating context
Failed to create GL 3.3 context ... using old-style GLX context
Failed to create an OpenGL context

**Comment by maxspahn** [comment]
Clearly, the glib driver is the problem. Have you tried to install the missing dependencies, such as swrast through `sudo apt install libgl1-mesa-dri`?

**Comment by harmfrima** [comment]
Yes, I tried that earlier. Unfortunately it gives the same error.

**Comment by harmfrima** [comment]
I deleted the whole virtual machine and reinstalled the VM. Now it is working

**Comment by maxspahn** [comment]
Glad to hear that! Do you know you could also use this environment in Windows?
