### ISSUE TITLE
Explaination for x, xdot, vel in code and docs

### ISSUE THREAD

**Issue by maxspahn** [maxspahn/gym_envs_urdf#55]
It is unclear, what `x`, `xdot` and `vel` actually mean. This should be improved by adding comments to the code, but also updating the documentation accordingly.

See https://github.com/maxspahn/gym_envs_urdf/blob/d4d49dc1bb7486f5ac006efaf79e8ce08603d7c9/urdfenvs/urdfCommon/differentialDriveRobot.py#L118-L135

**Comment by GijsGroote** [comment]
closing issue resolved with #56
