### ISSUE TITLE
Automated extraction of joint ids

### ISSUE THREAD

**Issue by maxspahn** [maxspahn/gym_envs_urdf#57]
Joint indices for reading in the limits, controlling the joints, and disable castor wheels is hard-coded at the moment. 
It would be much better if this was done automatically, or at least by name.

A starting point could be:
https://github.com/maxspahn/gym_envs_urdf/blob/d4d49dc1bb7486f5ac006efaf79e8ce08603d7c9/urdfenvs/tiagoReacher/resources/tiagoRobot.py#L23-L53

**Comment by maxspahn** [comment]
A possible solution to this can be found in 969cbd8ef3488027d55803bf8cf10aea1eb0b0e0

**Comment by SkyloveQiu** [comment]
That possible solution could not be used, since the connection with the server is not established when the code called `set_joint_indices` function.

**Comment by maxspahn** [comment]
Could we change that?
It is true, that the connection `p.loadURDF` must be called before we can access the joint names. Maybe, the joint indices could be extracted right after that function call in the reset function.

**Comment by SkyloveQiu** [comment]
Can I move the `loadURDF` to the `__init__` function?

**Comment by SkyloveQiu** [comment]
it will give error in `get_observation_space` function that object has no attribute `get_observation_space`

**Comment by SkyloveQiu** [comment]
I think we can add `set_joint_indices` before we call `get_observation_space` and it is working.
