### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by rensheemskerk** [maxspahn/gym_envs_urdf#59]
Here are the steps to run the code on windows (with spyder):
- Download Git for Windows: https://git-scm.com/download/win
- Open Git Bash
- Direct to a folder where you want the code to be stored
- Copy the HTTPS github link under the green 'code' box
- Run the command _git clone_ HTTPS link
Now the files are in the folder and linked to the github. To run the files:
- Open spyder
- In the console, direct to the folder you made earlier, and one step further to _gym_envs_urdf\_
- run _pip install ._
Now you should be able to run the codes found in the folders

**Comment by maxspahn** [comment]
Thanks @RJMHK 
I will add this to the documentation soon.

**Comment by maxspahn** [comment]
Have you tried it with the poetry installation?

**Comment by maxspahn** [comment]
Can you maybe comment on 2a8b78d, @rensheemskerk

**Comment by maxspahn** [comment]
Documentation added in #81

**Comment by maxspahn** [comment]
Closed with docs added a while ago.
