### ISSUE TITLE
Import Error** when using the function `initSim()` pointRobot

### ISSUE THREAD

**Issue by maxspahn** [maxspahn/gym_envs_urdf#6]
**Import Error** when using the function `initSim()`:

The function `initSim()` in [generic_env](https://github.com/maxspahn/gym_envs_urdf/blob/master/pointRobotUrdf/envs/genericEnv.py) of the pointRobotURDF environment is missing the import "pybullet" in line 61. 
Changing `self._p = bullet_client.BulletClient(connection_mode=pybullet.GUI)`
to `self._p = bullet_client.BulletClient(connection_mode=p.GUI)` should resolve this.

_Originally posted by @alxschwrz in https://github.com/maxspahn/gym_envs_urdf/issues/3#issuecomment-968720930_

**Comment by maxspahn** [comment]
This problem is also true for most other environments, see [mobileReacher](https://github.com/maxspahn/gym_envs_urdf/blob/f39dcbf32678c6320e573f4dcf373a7f056c7dd5/mobileReacher/envs/vel.py#L65) for example.

**Comment by maxspahn** [comment]
The function initSim() is actually not used in the environments. 
Should be removed entirely. Then this issue does not need solving.

**Comment by alxschwrz** [comment]
Should the function initSim() be removed entirely from all the environments?

**Comment by maxspahn** [comment]
Yes, that would be ideal.

**Comment by maxspahn** [comment]
It might be solved by working on #17

**Comment by maxspahn** [comment]
closed by #18
