### ISSUE TITLE
Pybullet version 3.2.1 causes installation problems

### ISSUE THREAD

**Issue by maxspahn** [maxspahn/gym_envs_urdf#62]
In some setups, `pybullet=^3.2.1` seems to cause problems.
If replaced with `pybullet=^3.2.0`, the problem is often resolved.

**Comment by maxspahn** [comment]
@alxschwrz Can you confirm that?

**Comment by maxspahn** [comment]
Duplicate of #58

**Comment by alxschwrz** [comment]
I can confirm this problem in my setup (MacBook M1.) When trying to install pybullet, both poetry and pip, did not find `Pybullet==3.2.1`, but it did work for `pybullet==3.2.0`
