### ISSUE TITLE
Adding citation file

### ISSUE THREAD

**Issue by GijsGroote** [maxspahn/gym_envs_urdf#65]
With [the citing function](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) users of the repository can easily cite gym_urdf repository. It is yet to be implemented for this repository.

**Comment by maxspahn** [comment]
This will be the doi: 10.4121/19362017
It is currently under review by the TU Delft data stewerts.

**Comment by maxspahn** [comment]
Addresse in #67
